name: "Bot: Send Close Pull Request Signal"

on:
  pull_request:
    types:
      [closed]

permissions:
  actions: write
  contents: read
  pull-requests: read

jobs:
  send-close-signal:
    name: "Send closing signal"
    runs-on: ubuntu-latest

    steps:
      - name: "Create PRtifact"
        run: |
          mkdir -p ./pr
          echo "${{ github.event.number }}" > ./pr/NUM
          echo "${{ github.event.pull_request.head.ref }}" > ./pr/BRANCH
      - name: Upload Diff
        uses: actions/upload-artifact@v4
        with:
          name: pr
          path: ./pr
