name: "Bot: Remove Temporary PR Branch"

on:
  workflow_run:
    workflows: ["Bot: Send Close Pull Request Signal"]
    types:
      - completed

permissions:
  actions: read     # to download artifacts from the triggering workflow
  contents: write   # to delete branches...

jobs:
  delete:
    name: "Delete branch from Pull Request"
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: 'Download artifact'
        uses: carpentries/actions/download-workflow-artifact@main
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: pr

      - name: "Get PR Number"
        id: get-pr
        run: |
          unzip pr.zip
          PR_NUM=$(cat ./NUM)
          echo "NUM=$PR_NUM" >> $GITHUB_OUTPUT

      - name: "Debug PR number"
        run: |
          echo "Downloaded PR number is: ${{ steps.get-pr.outputs.NUM }}"

      - name: 'Remove branch'
        uses: carpentries/actions/remove-branch@main
        with:
          prefix: pr        # <-- You can adjust this if your branch naming prefix is different
          pr: ${{ steps.get-pr.outputs.NUM }}
