name: "Bot: Remove Temporary PR Branch"

on:
  workflow_run:
    workflows: ["Bot: Send Close Pull Request Signal"]
    types:
      - completed

permissions:
  actions: read
  contents: write
  pull-requests: read  # NEW: Needed to read PR info..

jobs:
  delete:
    name: "Delete branch from Pull Request"
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'

    steps:
      - name: 'Download artifact'
        uses: carpentries/actions/download-workflow-artifact@main
        with:
          run: ${{ github.event.workflow_run.id }}
          name: pr

      - name: "Get PR Number"
        id: get-pr
        run: |
          unzip pr.zip
          echo "NUM=$(<./NUM)" >> $GITHUB_OUTPUT

      - name: "Get PR info (branch name)"
        id: pr-info
        run: |
          echo "Fetching PR info for PR #${{ steps.get-pr.outputs.NUM }}"
          PR_JSON=$(gh pr view ${{ steps.get-pr.outputs.NUM }} --json headRefName)
          echo "PR_JSON=$PR_JSON"
          HEAD_BRANCH=$(echo "$PR_JSON" | jq -r '.headRefName')
          echo "branch=$HEAD_BRANCH" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Debug Branch Name"
        run: |
          echo "Branch name to delete: ${{ steps.pr-info.outputs.branch }}"

      - name: 'Remove branch'
        uses: carpentries/actions/remove-branch@main
        with:
          branch: ${{ steps.pr-info.outputs.branch }}
