name: "Bot: Remove Temporary PR Branch"

on:
  workflow_run:
    workflows: ["Bot: Send Close Pull Request Signal"]
    types:
      - completed

permissions:
  actions: read
  contents: write

jobs:
  delete:
    name: "Delete branch from Pull Request"
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'

    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v4
        with:
          name: pr
          run: ${{ github.event.workflow_run.id }}

      - name: "Extract PR Number and Branch Name"
        id: vars
        run: |
          unzip pr.zip
          echo "PR_NUMBER=$(<./NUM)" >> $GITHUB_ENV
          echo "BRANCH_NAME=$(<./BRANCH)" >> $GITHUB_ENV

      - name: "Debug Output"
        run: |
          echo "PR number: $PR_NUMBER"
          echo "Branch name: $BRANCH_NAME"

      - name: 'Remove branch'
        uses: carpentries/actions/remove-branch@main
        with:
          branch: ${{ env.BRANCH_NAME }}
